// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Candle {
    pub id: u64,
    pub canonical_id: String,
    pub timestamp: i64,
    pub symbol: String,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
    pub timeframe: String,
    pub provider: String,
}

impl __sdk::InModule for Candle {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Candle`.
///
/// Provides typed access to columns for query building.
pub struct CandleCols {
    pub id: __sdk::__query_builder::Col<Candle, u64>,
    pub canonical_id: __sdk::__query_builder::Col<Candle, String>,
    pub timestamp: __sdk::__query_builder::Col<Candle, i64>,
    pub symbol: __sdk::__query_builder::Col<Candle, String>,
    pub open: __sdk::__query_builder::Col<Candle, f64>,
    pub high: __sdk::__query_builder::Col<Candle, f64>,
    pub low: __sdk::__query_builder::Col<Candle, f64>,
    pub close: __sdk::__query_builder::Col<Candle, f64>,
    pub volume: __sdk::__query_builder::Col<Candle, f64>,
    pub timeframe: __sdk::__query_builder::Col<Candle, String>,
    pub provider: __sdk::__query_builder::Col<Candle, String>,
}

impl __sdk::__query_builder::HasCols for Candle {
    type Cols = CandleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CandleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            canonical_id: __sdk::__query_builder::Col::new(table_name, "canonical_id"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
            symbol: __sdk::__query_builder::Col::new(table_name, "symbol"),
            open: __sdk::__query_builder::Col::new(table_name, "open"),
            high: __sdk::__query_builder::Col::new(table_name, "high"),
            low: __sdk::__query_builder::Col::new(table_name, "low"),
            close: __sdk::__query_builder::Col::new(table_name, "close"),
            volume: __sdk::__query_builder::Col::new(table_name, "volume"),
            timeframe: __sdk::__query_builder::Col::new(table_name, "timeframe"),
            provider: __sdk::__query_builder::Col::new(table_name, "provider"),
        }
    }
}

/// Indexed column accessor struct for the table `Candle`.
///
/// Provides typed access to indexed columns for query building.
pub struct CandleIxCols {
    pub canonical_id: __sdk::__query_builder::IxCol<Candle, String>,
    pub id: __sdk::__query_builder::IxCol<Candle, u64>,
}

impl __sdk::__query_builder::HasIxCols for Candle {
    type IxCols = CandleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CandleIxCols {
            canonical_id: __sdk::__query_builder::IxCol::new(table_name, "canonical_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Candle {}
