// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::candle_type::Candle;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `candles`.
///
/// Obtain a handle from the [`CandlesTableAccess::candles`] method on [`super::RemoteTables`],
/// like `ctx.db.candles()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.candles().on_insert(...)`.
pub struct CandlesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Candle>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `candles`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CandlesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CandlesTableHandle`], which mediates access to the table `candles`.
    fn candles(&self) -> CandlesTableHandle<'_>;
}

impl CandlesTableAccess for super::RemoteTables {
    fn candles(&self) -> CandlesTableHandle<'_> {
        CandlesTableHandle {
            imp: self.imp.get_table::<Candle>("candles"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CandlesInsertCallbackId(__sdk::CallbackId);
pub struct CandlesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CandlesTableHandle<'ctx> {
    type Row = Candle;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Candle> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CandlesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CandlesInsertCallbackId {
        CandlesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CandlesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CandlesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CandlesDeleteCallbackId {
        CandlesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CandlesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CandlesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CandlesTableHandle<'ctx> {
    type UpdateCallbackId = CandlesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CandlesUpdateCallbackId {
        CandlesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CandlesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `candles`,
/// which allows point queries on the field of the same name
/// via the [`CandlesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.candles().id().find(...)`.
pub struct CandlesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Candle, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CandlesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `candles`.
    pub fn id(&self) -> CandlesIdUnique<'ctx> {
        CandlesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CandlesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Candle> {
        self.imp.find(col_val)
    }
}

/// Access to the `canonical_id` unique index on the table `candles`,
/// which allows point queries on the field of the same name
/// via the [`CandlesCanonicalIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.candles().canonical_id().find(...)`.
pub struct CandlesCanonicalIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Candle, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CandlesTableHandle<'ctx> {
    /// Get a handle on the `canonical_id` unique index on the table `candles`.
    pub fn canonical_id(&self) -> CandlesCanonicalIdUnique<'ctx> {
        CandlesCanonicalIdUnique {
            imp: self.imp.get_unique_constraint::<String>("canonical_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CandlesCanonicalIdUnique<'ctx> {
    /// Find the subscribed row whose `canonical_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Candle> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Candle>("candles");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("canonical_id", |row| &row.canonical_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Candle>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Candle>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Candle`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait candlesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Candle`.
    fn candles(&self) -> __sdk::__query_builder::Table<Candle>;
}

impl candlesQueryTableAccess for __sdk::QueryTableAccessor {
    fn candles(&self) -> __sdk::__query_builder::Table<Candle> {
        __sdk::__query_builder::Table::new("candles")
    }
}
