// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClosePositionArgs {
    pub position_id: u64,
}

impl From<ClosePositionArgs> for super::Reducer {
    fn from(args: ClosePositionArgs) -> Self {
        Self::ClosePosition {
            position_id: args.position_id,
        }
    }
}

impl __sdk::InModule for ClosePositionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `close_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait close_position {
    /// Request that the remote module invoke the reducer `close_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`close_position:close_position_then`] to run a callback after the reducer completes.
    fn close_position(&self, position_id: u64) -> __sdk::Result<()> {
        self.close_position_then(position_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `close_position` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn close_position_then(
        &self,
        position_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl close_position for super::RemoteReducers {
    fn close_position_then(
        &self,
        position_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClosePositionArgs { position_id }, callback)
    }
}
