// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeletePaperDataByStrategyIdentityArgs {
    pub strategy_identity: String,
}

impl From<DeletePaperDataByStrategyIdentityArgs> for super::Reducer {
    fn from(args: DeletePaperDataByStrategyIdentityArgs) -> Self {
        Self::DeletePaperDataByStrategyIdentity {
            strategy_identity: args.strategy_identity,
        }
    }
}

impl __sdk::InModule for DeletePaperDataByStrategyIdentityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_paper_data_by_strategy_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_paper_data_by_strategy_identity {
    /// Request that the remote module invoke the reducer `delete_paper_data_by_strategy_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_paper_data_by_strategy_identity:delete_paper_data_by_strategy_identity_then`] to run a callback after the reducer completes.
    fn delete_paper_data_by_strategy_identity(
        &self,
        strategy_identity: String,
    ) -> __sdk::Result<()> {
        self.delete_paper_data_by_strategy_identity_then(strategy_identity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_paper_data_by_strategy_identity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_paper_data_by_strategy_identity_then(
        &self,
        strategy_identity: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_paper_data_by_strategy_identity for super::RemoteReducers {
    fn delete_paper_data_by_strategy_identity_then(
        &self,
        strategy_identity: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DeletePaperDataByStrategyIdentityArgs { strategy_identity },
            callback,
        )
    }
}
