// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertCandleArgs {
    pub canonical_id: String,
    pub timestamp: i64,
    pub symbol: String,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
    pub timeframe: String,
    pub provider: String,
}

impl From<InsertCandleArgs> for super::Reducer {
    fn from(args: InsertCandleArgs) -> Self {
        Self::InsertCandle {
            canonical_id: args.canonical_id,
            timestamp: args.timestamp,
            symbol: args.symbol,
            open: args.open,
            high: args.high,
            low: args.low,
            close: args.close,
            volume: args.volume,
            timeframe: args.timeframe,
            provider: args.provider,
        }
    }
}

impl __sdk::InModule for InsertCandleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_candle`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_candle {
    /// Request that the remote module invoke the reducer `insert_candle` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_candle:insert_candle_then`] to run a callback after the reducer completes.
    fn insert_candle(
        &self,
        canonical_id: String,
        timestamp: i64,
        symbol: String,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
        timeframe: String,
        provider: String,
    ) -> __sdk::Result<()> {
        self.insert_candle_then(
            canonical_id,
            timestamp,
            symbol,
            open,
            high,
            low,
            close,
            volume,
            timeframe,
            provider,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `insert_candle` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_candle_then(
        &self,
        canonical_id: String,
        timestamp: i64,
        symbol: String,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
        timeframe: String,
        provider: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_candle for super::RemoteReducers {
    fn insert_candle_then(
        &self,
        canonical_id: String,
        timestamp: i64,
        symbol: String,
        open: f64,
        high: f64,
        low: f64,
        close: f64,
        volume: f64,
        timeframe: String,
        provider: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            InsertCandleArgs {
                canonical_id,
                timestamp,
                symbol,
                open,
                high,
                low,
                close,
                volume,
                timeframe,
                provider,
            },
            callback,
        )
    }
}
