// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertTradeArgs {
    pub strategy: String,
    pub symbol: String,
    pub side: String,
    pub entry_price: f64,
    pub exit_price: f64,
    pub size: f64,
    pub pnl: f64,
    pub status: String,
    pub entry_time: i64,
    pub exit_time: i64,
    pub entry_reason: String,
    pub exit_reason: String,
}

impl From<InsertTradeArgs> for super::Reducer {
    fn from(args: InsertTradeArgs) -> Self {
        Self::InsertTrade {
            strategy: args.strategy,
            symbol: args.symbol,
            side: args.side,
            entry_price: args.entry_price,
            exit_price: args.exit_price,
            size: args.size,
            pnl: args.pnl,
            status: args.status,
            entry_time: args.entry_time,
            exit_time: args.exit_time,
            entry_reason: args.entry_reason,
            exit_reason: args.exit_reason,
        }
    }
}

impl __sdk::InModule for InsertTradeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_trade`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_trade {
    /// Request that the remote module invoke the reducer `insert_trade` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_trade:insert_trade_then`] to run a callback after the reducer completes.
    fn insert_trade(
        &self,
        strategy: String,
        symbol: String,
        side: String,
        entry_price: f64,
        exit_price: f64,
        size: f64,
        pnl: f64,
        status: String,
        entry_time: i64,
        exit_time: i64,
        entry_reason: String,
        exit_reason: String,
    ) -> __sdk::Result<()> {
        self.insert_trade_then(
            strategy,
            symbol,
            side,
            entry_price,
            exit_price,
            size,
            pnl,
            status,
            entry_time,
            exit_time,
            entry_reason,
            exit_reason,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `insert_trade` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_trade_then(
        &self,
        strategy: String,
        symbol: String,
        side: String,
        entry_price: f64,
        exit_price: f64,
        size: f64,
        pnl: f64,
        status: String,
        entry_time: i64,
        exit_time: i64,
        entry_reason: String,
        exit_reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_trade for super::RemoteReducers {
    fn insert_trade_then(
        &self,
        strategy: String,
        symbol: String,
        side: String,
        entry_price: f64,
        exit_price: f64,
        size: f64,
        pnl: f64,
        status: String,
        entry_time: i64,
        exit_time: i64,
        entry_reason: String,
        exit_reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            InsertTradeArgs {
                strategy,
                symbol,
                side,
                entry_price,
                exit_price,
                size,
                pnl,
                status,
                entry_time,
                exit_time,
                entry_reason,
                exit_reason,
            },
            callback,
        )
    }
}
