// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LivePosition {
    pub id: u64,
    pub strategy: String,
    pub symbol: String,
    pub side: String,
    pub entry_price: f64,
    pub size: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub entry_time: i64,
    pub entry_reason: String,
}

impl __sdk::InModule for LivePosition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LivePosition`.
///
/// Provides typed access to columns for query building.
pub struct LivePositionCols {
    pub id: __sdk::__query_builder::Col<LivePosition, u64>,
    pub strategy: __sdk::__query_builder::Col<LivePosition, String>,
    pub symbol: __sdk::__query_builder::Col<LivePosition, String>,
    pub side: __sdk::__query_builder::Col<LivePosition, String>,
    pub entry_price: __sdk::__query_builder::Col<LivePosition, f64>,
    pub size: __sdk::__query_builder::Col<LivePosition, f64>,
    pub stop_loss: __sdk::__query_builder::Col<LivePosition, f64>,
    pub take_profit: __sdk::__query_builder::Col<LivePosition, f64>,
    pub entry_time: __sdk::__query_builder::Col<LivePosition, i64>,
    pub entry_reason: __sdk::__query_builder::Col<LivePosition, String>,
}

impl __sdk::__query_builder::HasCols for LivePosition {
    type Cols = LivePositionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LivePositionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            strategy: __sdk::__query_builder::Col::new(table_name, "strategy"),
            symbol: __sdk::__query_builder::Col::new(table_name, "symbol"),
            side: __sdk::__query_builder::Col::new(table_name, "side"),
            entry_price: __sdk::__query_builder::Col::new(table_name, "entry_price"),
            size: __sdk::__query_builder::Col::new(table_name, "size"),
            stop_loss: __sdk::__query_builder::Col::new(table_name, "stop_loss"),
            take_profit: __sdk::__query_builder::Col::new(table_name, "take_profit"),
            entry_time: __sdk::__query_builder::Col::new(table_name, "entry_time"),
            entry_reason: __sdk::__query_builder::Col::new(table_name, "entry_reason"),
        }
    }
}

/// Indexed column accessor struct for the table `LivePosition`.
///
/// Provides typed access to indexed columns for query building.
pub struct LivePositionIxCols {
    pub id: __sdk::__query_builder::IxCol<LivePosition, u64>,
}

impl __sdk::__query_builder::HasIxCols for LivePosition {
    type IxCols = LivePositionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LivePositionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LivePosition {}
