// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LiveTrade {
    pub id: u64,
    pub strategy: String,
    pub symbol: String,
    pub side: String,
    pub entry_price: f64,
    pub exit_price: f64,
    pub size: f64,
    pub pnl: f64,
    pub status: String,
    pub entry_time: i64,
    pub exit_time: i64,
    pub entry_reason: String,
    pub exit_reason: String,
}

impl __sdk::InModule for LiveTrade {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LiveTrade`.
///
/// Provides typed access to columns for query building.
pub struct LiveTradeCols {
    pub id: __sdk::__query_builder::Col<LiveTrade, u64>,
    pub strategy: __sdk::__query_builder::Col<LiveTrade, String>,
    pub symbol: __sdk::__query_builder::Col<LiveTrade, String>,
    pub side: __sdk::__query_builder::Col<LiveTrade, String>,
    pub entry_price: __sdk::__query_builder::Col<LiveTrade, f64>,
    pub exit_price: __sdk::__query_builder::Col<LiveTrade, f64>,
    pub size: __sdk::__query_builder::Col<LiveTrade, f64>,
    pub pnl: __sdk::__query_builder::Col<LiveTrade, f64>,
    pub status: __sdk::__query_builder::Col<LiveTrade, String>,
    pub entry_time: __sdk::__query_builder::Col<LiveTrade, i64>,
    pub exit_time: __sdk::__query_builder::Col<LiveTrade, i64>,
    pub entry_reason: __sdk::__query_builder::Col<LiveTrade, String>,
    pub exit_reason: __sdk::__query_builder::Col<LiveTrade, String>,
}

impl __sdk::__query_builder::HasCols for LiveTrade {
    type Cols = LiveTradeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LiveTradeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            strategy: __sdk::__query_builder::Col::new(table_name, "strategy"),
            symbol: __sdk::__query_builder::Col::new(table_name, "symbol"),
            side: __sdk::__query_builder::Col::new(table_name, "side"),
            entry_price: __sdk::__query_builder::Col::new(table_name, "entry_price"),
            exit_price: __sdk::__query_builder::Col::new(table_name, "exit_price"),
            size: __sdk::__query_builder::Col::new(table_name, "size"),
            pnl: __sdk::__query_builder::Col::new(table_name, "pnl"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            entry_time: __sdk::__query_builder::Col::new(table_name, "entry_time"),
            exit_time: __sdk::__query_builder::Col::new(table_name, "exit_time"),
            entry_reason: __sdk::__query_builder::Col::new(table_name, "entry_reason"),
            exit_reason: __sdk::__query_builder::Col::new(table_name, "exit_reason"),
        }
    }
}

/// Indexed column accessor struct for the table `LiveTrade`.
///
/// Provides typed access to indexed columns for query building.
pub struct LiveTradeIxCols {
    pub id: __sdk::__query_builder::IxCol<LiveTrade, u64>,
}

impl __sdk::__query_builder::HasIxCols for LiveTrade {
    type IxCols = LiveTradeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LiveTradeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LiveTrade {}
