// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::live_position_type::LivePosition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `live_positions`.
///
/// Obtain a handle from the [`LivePositionsTableAccess::live_positions`] method on [`super::RemoteTables`],
/// like `ctx.db.live_positions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_positions().on_insert(...)`.
pub struct LivePositionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<LivePosition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `live_positions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LivePositionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LivePositionsTableHandle`], which mediates access to the table `live_positions`.
    fn live_positions(&self) -> LivePositionsTableHandle<'_>;
}

impl LivePositionsTableAccess for super::RemoteTables {
    fn live_positions(&self) -> LivePositionsTableHandle<'_> {
        LivePositionsTableHandle {
            imp: self.imp.get_table::<LivePosition>("live_positions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LivePositionsInsertCallbackId(__sdk::CallbackId);
pub struct LivePositionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LivePositionsTableHandle<'ctx> {
    type Row = LivePosition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LivePosition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LivePositionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LivePositionsInsertCallbackId {
        LivePositionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LivePositionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LivePositionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LivePositionsDeleteCallbackId {
        LivePositionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LivePositionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LivePositionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LivePositionsTableHandle<'ctx> {
    type UpdateCallbackId = LivePositionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LivePositionsUpdateCallbackId {
        LivePositionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LivePositionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `live_positions`,
/// which allows point queries on the field of the same name
/// via the [`LivePositionsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_positions().id().find(...)`.
pub struct LivePositionsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LivePosition, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LivePositionsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `live_positions`.
    pub fn id(&self) -> LivePositionsIdUnique<'ctx> {
        LivePositionsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LivePositionsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LivePosition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LivePosition>("live_positions");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LivePosition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LivePosition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LivePosition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait live_positionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LivePosition`.
    fn live_positions(&self) -> __sdk::__query_builder::Table<LivePosition>;
}

impl live_positionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn live_positions(&self) -> __sdk::__query_builder::Table<LivePosition> {
        __sdk::__query_builder::Table::new("live_positions")
    }
}
