// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::live_trade_type::LiveTrade;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `live_trades`.
///
/// Obtain a handle from the [`LiveTradesTableAccess::live_trades`] method on [`super::RemoteTables`],
/// like `ctx.db.live_trades()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_trades().on_insert(...)`.
pub struct LiveTradesTableHandle<'ctx> {
    imp: __sdk::TableHandle<LiveTrade>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `live_trades`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LiveTradesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LiveTradesTableHandle`], which mediates access to the table `live_trades`.
    fn live_trades(&self) -> LiveTradesTableHandle<'_>;
}

impl LiveTradesTableAccess for super::RemoteTables {
    fn live_trades(&self) -> LiveTradesTableHandle<'_> {
        LiveTradesTableHandle {
            imp: self.imp.get_table::<LiveTrade>("live_trades"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LiveTradesInsertCallbackId(__sdk::CallbackId);
pub struct LiveTradesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LiveTradesTableHandle<'ctx> {
    type Row = LiveTrade;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LiveTrade> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LiveTradesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveTradesInsertCallbackId {
        LiveTradesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LiveTradesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LiveTradesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveTradesDeleteCallbackId {
        LiveTradesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LiveTradesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LiveTradesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LiveTradesTableHandle<'ctx> {
    type UpdateCallbackId = LiveTradesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LiveTradesUpdateCallbackId {
        LiveTradesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LiveTradesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `live_trades`,
/// which allows point queries on the field of the same name
/// via the [`LiveTradesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_trades().id().find(...)`.
pub struct LiveTradesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LiveTrade, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LiveTradesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `live_trades`.
    pub fn id(&self) -> LiveTradesIdUnique<'ctx> {
        LiveTradesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LiveTradesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LiveTrade> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LiveTrade>("live_trades");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LiveTrade>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LiveTrade>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LiveTrade`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait live_tradesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LiveTrade`.
    fn live_trades(&self) -> __sdk::__query_builder::Table<LiveTrade>;
}

impl live_tradesQueryTableAccess for __sdk::QueryTableAccessor {
    fn live_trades(&self) -> __sdk::__query_builder::Table<LiveTrade> {
        __sdk::__query_builder::Table::new("live_trades")
    }
}
