// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OpenPaperPositionArgs {
    pub projection_key: String,
    pub strategy_identity: String,
    pub runtime_asset: String,
    pub side: String,
    pub entry_price: f64,
    pub quantity: f64,
    pub entry_time: i64,
    pub stop_loss: Option<f64>,
    pub take_profit: Option<f64>,
    pub entry_metadata: Option<String>,
    pub entry_base_price: Option<f64>,
    pub entry_effective_fill_price: Option<f64>,
    pub entry_spread_adjustment: Option<f64>,
    pub entry_fixed_fee: Option<f64>,
    pub entry_percent_fee: Option<f64>,
    pub entry_total_cost: Option<f64>,
}

impl From<OpenPaperPositionArgs> for super::Reducer {
    fn from(args: OpenPaperPositionArgs) -> Self {
        Self::OpenPaperPosition {
            projection_key: args.projection_key,
            strategy_identity: args.strategy_identity,
            runtime_asset: args.runtime_asset,
            side: args.side,
            entry_price: args.entry_price,
            quantity: args.quantity,
            entry_time: args.entry_time,
            stop_loss: args.stop_loss,
            take_profit: args.take_profit,
            entry_metadata: args.entry_metadata,
            entry_base_price: args.entry_base_price,
            entry_effective_fill_price: args.entry_effective_fill_price,
            entry_spread_adjustment: args.entry_spread_adjustment,
            entry_fixed_fee: args.entry_fixed_fee,
            entry_percent_fee: args.entry_percent_fee,
            entry_total_cost: args.entry_total_cost,
        }
    }
}

impl __sdk::InModule for OpenPaperPositionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `open_paper_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait open_paper_position {
    /// Request that the remote module invoke the reducer `open_paper_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`open_paper_position:open_paper_position_then`] to run a callback after the reducer completes.
    fn open_paper_position(
        &self,
        projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        quantity: f64,
        entry_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,
        entry_metadata: Option<String>,
        entry_base_price: Option<f64>,
        entry_effective_fill_price: Option<f64>,
        entry_spread_adjustment: Option<f64>,
        entry_fixed_fee: Option<f64>,
        entry_percent_fee: Option<f64>,
        entry_total_cost: Option<f64>,
    ) -> __sdk::Result<()> {
        self.open_paper_position_then(
            projection_key,
            strategy_identity,
            runtime_asset,
            side,
            entry_price,
            quantity,
            entry_time,
            stop_loss,
            take_profit,
            entry_metadata,
            entry_base_price,
            entry_effective_fill_price,
            entry_spread_adjustment,
            entry_fixed_fee,
            entry_percent_fee,
            entry_total_cost,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `open_paper_position` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn open_paper_position_then(
        &self,
        projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        quantity: f64,
        entry_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,
        entry_metadata: Option<String>,
        entry_base_price: Option<f64>,
        entry_effective_fill_price: Option<f64>,
        entry_spread_adjustment: Option<f64>,
        entry_fixed_fee: Option<f64>,
        entry_percent_fee: Option<f64>,
        entry_total_cost: Option<f64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl open_paper_position for super::RemoteReducers {
    fn open_paper_position_then(
        &self,
        projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        quantity: f64,
        entry_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,
        entry_metadata: Option<String>,
        entry_base_price: Option<f64>,
        entry_effective_fill_price: Option<f64>,
        entry_spread_adjustment: Option<f64>,
        entry_fixed_fee: Option<f64>,
        entry_percent_fee: Option<f64>,
        entry_total_cost: Option<f64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            OpenPaperPositionArgs {
                projection_key,
                strategy_identity,
                runtime_asset,
                side,
                entry_price,
                quantity,
                entry_time,
                stop_loss,
                take_profit,
                entry_metadata,
                entry_base_price,
                entry_effective_fill_price,
                entry_spread_adjustment,
                entry_fixed_fee,
                entry_percent_fee,
                entry_total_cost,
            },
            callback,
        )
    }
}
