// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OpenPositionArgs {
    pub strategy: String,
    pub symbol: String,
    pub side: String,
    pub entry_price: f64,
    pub size: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub entry_time: i64,
    pub entry_reason: String,
}

impl From<OpenPositionArgs> for super::Reducer {
    fn from(args: OpenPositionArgs) -> Self {
        Self::OpenPosition {
            strategy: args.strategy,
            symbol: args.symbol,
            side: args.side,
            entry_price: args.entry_price,
            size: args.size,
            stop_loss: args.stop_loss,
            take_profit: args.take_profit,
            entry_time: args.entry_time,
            entry_reason: args.entry_reason,
        }
    }
}

impl __sdk::InModule for OpenPositionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `open_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait open_position {
    /// Request that the remote module invoke the reducer `open_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`open_position:open_position_then`] to run a callback after the reducer completes.
    fn open_position(
        &self,
        strategy: String,
        symbol: String,
        side: String,
        entry_price: f64,
        size: f64,
        stop_loss: f64,
        take_profit: f64,
        entry_time: i64,
        entry_reason: String,
    ) -> __sdk::Result<()> {
        self.open_position_then(
            strategy,
            symbol,
            side,
            entry_price,
            size,
            stop_loss,
            take_profit,
            entry_time,
            entry_reason,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `open_position` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn open_position_then(
        &self,
        strategy: String,
        symbol: String,
        side: String,
        entry_price: f64,
        size: f64,
        stop_loss: f64,
        take_profit: f64,
        entry_time: i64,
        entry_reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl open_position for super::RemoteReducers {
    fn open_position_then(
        &self,
        strategy: String,
        symbol: String,
        side: String,
        entry_price: f64,
        size: f64,
        stop_loss: f64,
        take_profit: f64,
        entry_time: i64,
        entry_reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            OpenPositionArgs {
                strategy,
                symbol,
                side,
                entry_price,
                size,
                stop_loss,
                take_profit,
                entry_time,
                entry_reason,
            },
            callback,
        )
    }
}
