// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::paper_exit_kind_type::PaperExitKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PaperTrade {
    pub projection_key: String,
    pub strategy_identity: String,
    pub runtime_asset: String,
    pub side: String,
    pub entry_price: f64,
    pub exit_price: f64,
    pub quantity: f64,
    pub realized_pnl: f64,
    pub entry_time: i64,
    pub exit_time: i64,
    pub stop_loss: Option<f64>,
    pub take_profit: Option<f64>,
    pub exit_kind: PaperExitKind,
    pub entry_metadata: Option<String>,
    pub exit_metadata: Option<String>,
    pub entry_base_price: Option<f64>,
    pub entry_effective_fill_price: Option<f64>,
    pub entry_spread_adjustment: Option<f64>,
    pub entry_fixed_fee: Option<f64>,
    pub entry_percent_fee: Option<f64>,
    pub entry_total_cost: Option<f64>,
    pub exit_base_price: Option<f64>,
    pub exit_effective_fill_price: Option<f64>,
    pub exit_spread_adjustment: Option<f64>,
    pub exit_fixed_fee: Option<f64>,
    pub exit_percent_fee: Option<f64>,
    pub exit_total_cost: Option<f64>,
    pub gross_pnl: Option<f64>,
    pub total_costs: Option<f64>,
    pub net_realized_pnl: Option<f64>,
}

impl __sdk::InModule for PaperTrade {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PaperTrade`.
///
/// Provides typed access to columns for query building.
pub struct PaperTradeCols {
    pub projection_key: __sdk::__query_builder::Col<PaperTrade, String>,
    pub strategy_identity: __sdk::__query_builder::Col<PaperTrade, String>,
    pub runtime_asset: __sdk::__query_builder::Col<PaperTrade, String>,
    pub side: __sdk::__query_builder::Col<PaperTrade, String>,
    pub entry_price: __sdk::__query_builder::Col<PaperTrade, f64>,
    pub exit_price: __sdk::__query_builder::Col<PaperTrade, f64>,
    pub quantity: __sdk::__query_builder::Col<PaperTrade, f64>,
    pub realized_pnl: __sdk::__query_builder::Col<PaperTrade, f64>,
    pub entry_time: __sdk::__query_builder::Col<PaperTrade, i64>,
    pub exit_time: __sdk::__query_builder::Col<PaperTrade, i64>,
    pub stop_loss: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub take_profit: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub exit_kind: __sdk::__query_builder::Col<PaperTrade, PaperExitKind>,
    pub entry_metadata: __sdk::__query_builder::Col<PaperTrade, Option<String>>,
    pub exit_metadata: __sdk::__query_builder::Col<PaperTrade, Option<String>>,
    pub entry_base_price: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub entry_effective_fill_price: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub entry_spread_adjustment: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub entry_fixed_fee: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub entry_percent_fee: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub entry_total_cost: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub exit_base_price: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub exit_effective_fill_price: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub exit_spread_adjustment: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub exit_fixed_fee: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub exit_percent_fee: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub exit_total_cost: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub gross_pnl: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub total_costs: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
    pub net_realized_pnl: __sdk::__query_builder::Col<PaperTrade, Option<f64>>,
}

impl __sdk::__query_builder::HasCols for PaperTrade {
    type Cols = PaperTradeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PaperTradeCols {
            projection_key: __sdk::__query_builder::Col::new(table_name, "projection_key"),
            strategy_identity: __sdk::__query_builder::Col::new(table_name, "strategy_identity"),
            runtime_asset: __sdk::__query_builder::Col::new(table_name, "runtime_asset"),
            side: __sdk::__query_builder::Col::new(table_name, "side"),
            entry_price: __sdk::__query_builder::Col::new(table_name, "entry_price"),
            exit_price: __sdk::__query_builder::Col::new(table_name, "exit_price"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            realized_pnl: __sdk::__query_builder::Col::new(table_name, "realized_pnl"),
            entry_time: __sdk::__query_builder::Col::new(table_name, "entry_time"),
            exit_time: __sdk::__query_builder::Col::new(table_name, "exit_time"),
            stop_loss: __sdk::__query_builder::Col::new(table_name, "stop_loss"),
            take_profit: __sdk::__query_builder::Col::new(table_name, "take_profit"),
            exit_kind: __sdk::__query_builder::Col::new(table_name, "exit_kind"),
            entry_metadata: __sdk::__query_builder::Col::new(table_name, "entry_metadata"),
            exit_metadata: __sdk::__query_builder::Col::new(table_name, "exit_metadata"),
            entry_base_price: __sdk::__query_builder::Col::new(table_name, "entry_base_price"),
            entry_effective_fill_price: __sdk::__query_builder::Col::new(
                table_name,
                "entry_effective_fill_price",
            ),
            entry_spread_adjustment: __sdk::__query_builder::Col::new(
                table_name,
                "entry_spread_adjustment",
            ),
            entry_fixed_fee: __sdk::__query_builder::Col::new(table_name, "entry_fixed_fee"),
            entry_percent_fee: __sdk::__query_builder::Col::new(table_name, "entry_percent_fee"),
            entry_total_cost: __sdk::__query_builder::Col::new(table_name, "entry_total_cost"),
            exit_base_price: __sdk::__query_builder::Col::new(table_name, "exit_base_price"),
            exit_effective_fill_price: __sdk::__query_builder::Col::new(
                table_name,
                "exit_effective_fill_price",
            ),
            exit_spread_adjustment: __sdk::__query_builder::Col::new(
                table_name,
                "exit_spread_adjustment",
            ),
            exit_fixed_fee: __sdk::__query_builder::Col::new(table_name, "exit_fixed_fee"),
            exit_percent_fee: __sdk::__query_builder::Col::new(table_name, "exit_percent_fee"),
            exit_total_cost: __sdk::__query_builder::Col::new(table_name, "exit_total_cost"),
            gross_pnl: __sdk::__query_builder::Col::new(table_name, "gross_pnl"),
            total_costs: __sdk::__query_builder::Col::new(table_name, "total_costs"),
            net_realized_pnl: __sdk::__query_builder::Col::new(table_name, "net_realized_pnl"),
        }
    }
}

/// Indexed column accessor struct for the table `PaperTrade`.
///
/// Provides typed access to indexed columns for query building.
pub struct PaperTradeIxCols {
    pub projection_key: __sdk::__query_builder::IxCol<PaperTrade, String>,
}

impl __sdk::__query_builder::HasIxCols for PaperTrade {
    type IxCols = PaperTradeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PaperTradeIxCols {
            projection_key: __sdk::__query_builder::IxCol::new(table_name, "projection_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PaperTrade {}
