// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::paper_open_position_type::PaperOpenPosition;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `paper_open_positions`.
///
/// Obtain a handle from the [`PaperOpenPositionsTableAccess::paper_open_positions`] method on [`super::RemoteTables`],
/// like `ctx.db.paper_open_positions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.paper_open_positions().on_insert(...)`.
pub struct PaperOpenPositionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<PaperOpenPosition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `paper_open_positions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PaperOpenPositionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PaperOpenPositionsTableHandle`], which mediates access to the table `paper_open_positions`.
    fn paper_open_positions(&self) -> PaperOpenPositionsTableHandle<'_>;
}

impl PaperOpenPositionsTableAccess for super::RemoteTables {
    fn paper_open_positions(&self) -> PaperOpenPositionsTableHandle<'_> {
        PaperOpenPositionsTableHandle {
            imp: self
                .imp
                .get_table::<PaperOpenPosition>("paper_open_positions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PaperOpenPositionsInsertCallbackId(__sdk::CallbackId);
pub struct PaperOpenPositionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PaperOpenPositionsTableHandle<'ctx> {
    type Row = PaperOpenPosition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PaperOpenPosition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PaperOpenPositionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PaperOpenPositionsInsertCallbackId {
        PaperOpenPositionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PaperOpenPositionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PaperOpenPositionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PaperOpenPositionsDeleteCallbackId {
        PaperOpenPositionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PaperOpenPositionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PaperOpenPositionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PaperOpenPositionsTableHandle<'ctx> {
    type UpdateCallbackId = PaperOpenPositionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PaperOpenPositionsUpdateCallbackId {
        PaperOpenPositionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PaperOpenPositionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `projection_key` unique index on the table `paper_open_positions`,
/// which allows point queries on the field of the same name
/// via the [`PaperOpenPositionsProjectionKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.paper_open_positions().projection_key().find(...)`.
pub struct PaperOpenPositionsProjectionKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PaperOpenPosition, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PaperOpenPositionsTableHandle<'ctx> {
    /// Get a handle on the `projection_key` unique index on the table `paper_open_positions`.
    pub fn projection_key(&self) -> PaperOpenPositionsProjectionKeyUnique<'ctx> {
        PaperOpenPositionsProjectionKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("projection_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PaperOpenPositionsProjectionKeyUnique<'ctx> {
    /// Find the subscribed row whose `projection_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PaperOpenPosition> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PaperOpenPosition>("paper_open_positions");
    _table.add_unique_constraint::<String>("projection_key", |row| &row.projection_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PaperOpenPosition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PaperOpenPosition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PaperOpenPosition`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait paper_open_positionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PaperOpenPosition`.
    fn paper_open_positions(&self) -> __sdk::__query_builder::Table<PaperOpenPosition>;
}

impl paper_open_positionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn paper_open_positions(&self) -> __sdk::__query_builder::Table<PaperOpenPosition> {
        __sdk::__query_builder::Table::new("paper_open_positions")
    }
}
