// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PaperOpenPosition {
    pub projection_key: String,
    pub strategy_identity: String,
    pub runtime_asset: String,
    pub side: String,
    pub entry_price: f64,
    pub quantity: f64,
    pub entry_time: i64,
    pub stop_loss: Option<f64>,
    pub take_profit: Option<f64>,
    pub entry_metadata: Option<String>,
}

impl __sdk::InModule for PaperOpenPosition {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PaperOpenPosition`.
///
/// Provides typed access to columns for query building.
pub struct PaperOpenPositionCols {
    pub projection_key: __sdk::__query_builder::Col<PaperOpenPosition, String>,
    pub strategy_identity: __sdk::__query_builder::Col<PaperOpenPosition, String>,
    pub runtime_asset: __sdk::__query_builder::Col<PaperOpenPosition, String>,
    pub side: __sdk::__query_builder::Col<PaperOpenPosition, String>,
    pub entry_price: __sdk::__query_builder::Col<PaperOpenPosition, f64>,
    pub quantity: __sdk::__query_builder::Col<PaperOpenPosition, f64>,
    pub entry_time: __sdk::__query_builder::Col<PaperOpenPosition, i64>,
    pub stop_loss: __sdk::__query_builder::Col<PaperOpenPosition, Option<f64>>,
    pub take_profit: __sdk::__query_builder::Col<PaperOpenPosition, Option<f64>>,
    pub entry_metadata: __sdk::__query_builder::Col<PaperOpenPosition, Option<String>>,
}

impl __sdk::__query_builder::HasCols for PaperOpenPosition {
    type Cols = PaperOpenPositionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PaperOpenPositionCols {
            projection_key: __sdk::__query_builder::Col::new(table_name, "projection_key"),
            strategy_identity: __sdk::__query_builder::Col::new(table_name, "strategy_identity"),
            runtime_asset: __sdk::__query_builder::Col::new(table_name, "runtime_asset"),
            side: __sdk::__query_builder::Col::new(table_name, "side"),
            entry_price: __sdk::__query_builder::Col::new(table_name, "entry_price"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            entry_time: __sdk::__query_builder::Col::new(table_name, "entry_time"),
            stop_loss: __sdk::__query_builder::Col::new(table_name, "stop_loss"),
            take_profit: __sdk::__query_builder::Col::new(table_name, "take_profit"),
            entry_metadata: __sdk::__query_builder::Col::new(table_name, "entry_metadata"),
        }
    }
}

/// Indexed column accessor struct for the table `PaperOpenPosition`.
///
/// Provides typed access to indexed columns for query building.
pub struct PaperOpenPositionIxCols {
    pub projection_key: __sdk::__query_builder::IxCol<PaperOpenPosition, String>,
}

impl __sdk::__query_builder::HasIxCols for PaperOpenPosition {
    type IxCols = PaperOpenPositionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PaperOpenPositionIxCols {
            projection_key: __sdk::__query_builder::IxCol::new(table_name, "projection_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PaperOpenPosition {}
