// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::paper_exit_kind_type::PaperExitKind;
use super::paper_trade_type::PaperTrade;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `paper_trades`.
///
/// Obtain a handle from the [`PaperTradesTableAccess::paper_trades`] method on [`super::RemoteTables`],
/// like `ctx.db.paper_trades()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.paper_trades().on_insert(...)`.
pub struct PaperTradesTableHandle<'ctx> {
    imp: __sdk::TableHandle<PaperTrade>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `paper_trades`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PaperTradesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PaperTradesTableHandle`], which mediates access to the table `paper_trades`.
    fn paper_trades(&self) -> PaperTradesTableHandle<'_>;
}

impl PaperTradesTableAccess for super::RemoteTables {
    fn paper_trades(&self) -> PaperTradesTableHandle<'_> {
        PaperTradesTableHandle {
            imp: self.imp.get_table::<PaperTrade>("paper_trades"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PaperTradesInsertCallbackId(__sdk::CallbackId);
pub struct PaperTradesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PaperTradesTableHandle<'ctx> {
    type Row = PaperTrade;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PaperTrade> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PaperTradesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PaperTradesInsertCallbackId {
        PaperTradesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PaperTradesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PaperTradesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PaperTradesDeleteCallbackId {
        PaperTradesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PaperTradesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PaperTradesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PaperTradesTableHandle<'ctx> {
    type UpdateCallbackId = PaperTradesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PaperTradesUpdateCallbackId {
        PaperTradesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PaperTradesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `projection_key` unique index on the table `paper_trades`,
/// which allows point queries on the field of the same name
/// via the [`PaperTradesProjectionKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.paper_trades().projection_key().find(...)`.
pub struct PaperTradesProjectionKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PaperTrade, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PaperTradesTableHandle<'ctx> {
    /// Get a handle on the `projection_key` unique index on the table `paper_trades`.
    pub fn projection_key(&self) -> PaperTradesProjectionKeyUnique<'ctx> {
        PaperTradesProjectionKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("projection_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PaperTradesProjectionKeyUnique<'ctx> {
    /// Find the subscribed row whose `projection_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PaperTrade> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PaperTrade>("paper_trades");
    _table.add_unique_constraint::<String>("projection_key", |row| &row.projection_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PaperTrade>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PaperTrade>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PaperTrade`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait paper_tradesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PaperTrade`.
    fn paper_trades(&self) -> __sdk::__query_builder::Table<PaperTrade>;
}

impl paper_tradesQueryTableAccess for __sdk::QueryTableAccessor {
    fn paper_trades(&self) -> __sdk::__query_builder::Table<PaperTrade> {
        __sdk::__query_builder::Table::new("paper_trades")
    }
}
