// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::paper_exit_kind_type::PaperExitKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordPaperPositionClosedArgs {
    pub open_projection_key: String,
    pub trade_projection_key: String,
    pub strategy_identity: String,
    pub runtime_asset: String,
    pub side: String,
    pub entry_price: f64,
    pub exit_price: f64,
    pub quantity: f64,
    pub realized_pnl: f64,
    pub entry_time: i64,
    pub exit_time: i64,
    pub stop_loss: Option<f64>,
    pub take_profit: Option<f64>,
    pub exit_kind: PaperExitKind,
    pub entry_metadata: Option<String>,
    pub exit_metadata: Option<String>,
    pub entry_base_price: Option<f64>,
    pub entry_effective_fill_price: Option<f64>,
    pub entry_spread_adjustment: Option<f64>,
    pub entry_fixed_fee: Option<f64>,
    pub entry_percent_fee: Option<f64>,
    pub entry_total_cost: Option<f64>,
    pub exit_base_price: Option<f64>,
    pub exit_effective_fill_price: Option<f64>,
    pub exit_spread_adjustment: Option<f64>,
    pub exit_fixed_fee: Option<f64>,
    pub exit_percent_fee: Option<f64>,
    pub exit_total_cost: Option<f64>,
    pub gross_pnl: Option<f64>,
    pub total_costs: Option<f64>,
    pub net_realized_pnl: Option<f64>,
}

impl From<RecordPaperPositionClosedArgs> for super::Reducer {
    fn from(args: RecordPaperPositionClosedArgs) -> Self {
        Self::RecordPaperPositionClosed {
            open_projection_key: args.open_projection_key,
            trade_projection_key: args.trade_projection_key,
            strategy_identity: args.strategy_identity,
            runtime_asset: args.runtime_asset,
            side: args.side,
            entry_price: args.entry_price,
            exit_price: args.exit_price,
            quantity: args.quantity,
            realized_pnl: args.realized_pnl,
            entry_time: args.entry_time,
            exit_time: args.exit_time,
            stop_loss: args.stop_loss,
            take_profit: args.take_profit,
            exit_kind: args.exit_kind,
            entry_metadata: args.entry_metadata,
            exit_metadata: args.exit_metadata,
            entry_base_price: args.entry_base_price,
            entry_effective_fill_price: args.entry_effective_fill_price,
            entry_spread_adjustment: args.entry_spread_adjustment,
            entry_fixed_fee: args.entry_fixed_fee,
            entry_percent_fee: args.entry_percent_fee,
            entry_total_cost: args.entry_total_cost,
            exit_base_price: args.exit_base_price,
            exit_effective_fill_price: args.exit_effective_fill_price,
            exit_spread_adjustment: args.exit_spread_adjustment,
            exit_fixed_fee: args.exit_fixed_fee,
            exit_percent_fee: args.exit_percent_fee,
            exit_total_cost: args.exit_total_cost,
            gross_pnl: args.gross_pnl,
            total_costs: args.total_costs,
            net_realized_pnl: args.net_realized_pnl,
        }
    }
}

impl __sdk::InModule for RecordPaperPositionClosedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_paper_position_closed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_paper_position_closed {
    /// Request that the remote module invoke the reducer `record_paper_position_closed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_paper_position_closed:record_paper_position_closed_then`] to run a callback after the reducer completes.
    fn record_paper_position_closed(
        &self,
        open_projection_key: String,
        trade_projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        exit_price: f64,
        quantity: f64,
        realized_pnl: f64,
        entry_time: i64,
        exit_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,
        exit_kind: PaperExitKind,
        entry_metadata: Option<String>,
        exit_metadata: Option<String>,
        entry_base_price: Option<f64>,
        entry_effective_fill_price: Option<f64>,
        entry_spread_adjustment: Option<f64>,
        entry_fixed_fee: Option<f64>,
        entry_percent_fee: Option<f64>,
        entry_total_cost: Option<f64>,
        exit_base_price: Option<f64>,
        exit_effective_fill_price: Option<f64>,
        exit_spread_adjustment: Option<f64>,
        exit_fixed_fee: Option<f64>,
        exit_percent_fee: Option<f64>,
        exit_total_cost: Option<f64>,
        gross_pnl: Option<f64>,
        total_costs: Option<f64>,
        net_realized_pnl: Option<f64>,
    ) -> __sdk::Result<()> {
        self.record_paper_position_closed_then(
            open_projection_key,
            trade_projection_key,
            strategy_identity,
            runtime_asset,
            side,
            entry_price,
            exit_price,
            quantity,
            realized_pnl,
            entry_time,
            exit_time,
            stop_loss,
            take_profit,
            exit_kind,
            entry_metadata,
            exit_metadata,
            entry_base_price,
            entry_effective_fill_price,
            entry_spread_adjustment,
            entry_fixed_fee,
            entry_percent_fee,
            entry_total_cost,
            exit_base_price,
            exit_effective_fill_price,
            exit_spread_adjustment,
            exit_fixed_fee,
            exit_percent_fee,
            exit_total_cost,
            gross_pnl,
            total_costs,
            net_realized_pnl,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_paper_position_closed` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_paper_position_closed_then(
        &self,
        open_projection_key: String,
        trade_projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        exit_price: f64,
        quantity: f64,
        realized_pnl: f64,
        entry_time: i64,
        exit_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,
        exit_kind: PaperExitKind,
        entry_metadata: Option<String>,
        exit_metadata: Option<String>,
        entry_base_price: Option<f64>,
        entry_effective_fill_price: Option<f64>,
        entry_spread_adjustment: Option<f64>,
        entry_fixed_fee: Option<f64>,
        entry_percent_fee: Option<f64>,
        entry_total_cost: Option<f64>,
        exit_base_price: Option<f64>,
        exit_effective_fill_price: Option<f64>,
        exit_spread_adjustment: Option<f64>,
        exit_fixed_fee: Option<f64>,
        exit_percent_fee: Option<f64>,
        exit_total_cost: Option<f64>,
        gross_pnl: Option<f64>,
        total_costs: Option<f64>,
        net_realized_pnl: Option<f64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_paper_position_closed for super::RemoteReducers {
    fn record_paper_position_closed_then(
        &self,
        open_projection_key: String,
        trade_projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        exit_price: f64,
        quantity: f64,
        realized_pnl: f64,
        entry_time: i64,
        exit_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,
        exit_kind: PaperExitKind,
        entry_metadata: Option<String>,
        exit_metadata: Option<String>,
        entry_base_price: Option<f64>,
        entry_effective_fill_price: Option<f64>,
        entry_spread_adjustment: Option<f64>,
        entry_fixed_fee: Option<f64>,
        entry_percent_fee: Option<f64>,
        entry_total_cost: Option<f64>,
        exit_base_price: Option<f64>,
        exit_effective_fill_price: Option<f64>,
        exit_spread_adjustment: Option<f64>,
        exit_fixed_fee: Option<f64>,
        exit_percent_fee: Option<f64>,
        exit_total_cost: Option<f64>,
        gross_pnl: Option<f64>,
        total_costs: Option<f64>,
        net_realized_pnl: Option<f64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordPaperPositionClosedArgs {
                open_projection_key,
                trade_projection_key,
                strategy_identity,
                runtime_asset,
                side,
                entry_price,
                exit_price,
                quantity,
                realized_pnl,
                entry_time,
                exit_time,
                stop_loss,
                take_profit,
                exit_kind,
                entry_metadata,
                exit_metadata,
                entry_base_price,
                entry_effective_fill_price,
                entry_spread_adjustment,
                entry_fixed_fee,
                entry_percent_fee,
                entry_total_cost,
                exit_base_price,
                exit_effective_fill_price,
                exit_spread_adjustment,
                exit_fixed_fee,
                exit_percent_fee,
                exit_total_cost,
                gross_pnl,
                total_costs,
                net_realized_pnl,
            },
            callback,
        )
    }
}
