// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePaperPositionRiskBoundariesArgs {
    pub open_projection_key: String,
    pub strategy_identity: String,
    pub runtime_asset: String,
    pub side: String,
    pub entry_price: f64,
    pub quantity: f64,
    pub entry_time: i64,
    pub stop_loss: Option<f64>,
    pub take_profit: Option<f64>,
}

impl From<UpdatePaperPositionRiskBoundariesArgs> for super::Reducer {
    fn from(args: UpdatePaperPositionRiskBoundariesArgs) -> Self {
        Self::UpdatePaperPositionRiskBoundaries {
            open_projection_key: args.open_projection_key,
            strategy_identity: args.strategy_identity,
            runtime_asset: args.runtime_asset,
            side: args.side,
            entry_price: args.entry_price,
            quantity: args.quantity,
            entry_time: args.entry_time,
            stop_loss: args.stop_loss,
            take_profit: args.take_profit,
        }
    }
}

impl __sdk::InModule for UpdatePaperPositionRiskBoundariesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_paper_position_risk_boundaries`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_paper_position_risk_boundaries {
    /// Request that the remote module invoke the reducer `update_paper_position_risk_boundaries` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_paper_position_risk_boundaries:update_paper_position_risk_boundaries_then`] to run a callback after the reducer completes.
    fn update_paper_position_risk_boundaries(
        &self,
        open_projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        quantity: f64,
        entry_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,
    ) -> __sdk::Result<()> {
        self.update_paper_position_risk_boundaries_then(
            open_projection_key,
            strategy_identity,
            runtime_asset,
            side,
            entry_price,
            quantity,
            entry_time,
            stop_loss,
            take_profit,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_paper_position_risk_boundaries` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_paper_position_risk_boundaries_then(
        &self,
        open_projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        quantity: f64,
        entry_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_paper_position_risk_boundaries for super::RemoteReducers {
    fn update_paper_position_risk_boundaries_then(
        &self,
        open_projection_key: String,
        strategy_identity: String,
        runtime_asset: String,
        side: String,
        entry_price: f64,
        quantity: f64,
        entry_time: i64,
        stop_loss: Option<f64>,
        take_profit: Option<f64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdatePaperPositionRiskBoundariesArgs {
                open_projection_key,
                strategy_identity,
                runtime_asset,
                side,
                entry_price,
                quantity,
                entry_time,
                stop_loss,
                take_profit,
            },
            callback,
        )
    }
}
